### ISSUE TITLE
I think this is not working for v7.0

### ISSUE THREAD

**Issue by rajuaryan21** [CentricWebEstate/clickbankgo#1]
Hi,

I tried to use your code and it looks like this is not working. The timestamp being encoded is in strange format, something like hex in terminal.

Could you please have a look at it for a second?

Thanks you so much for such an awesome library.

**Comment by jaitaiwan** [comment]
Hey @rajuaryan21,

Happy to help, it's been a long time since I've worked on this library. Are you able to send a sample of your implementation and the output you're seeing?

**Comment by rajuaryan21** [comment]
![Screenshot from 2023-07-27 15-20-39](https://github.com/CentricWebEstate/clickbankgo/assets/3599630/1e9d30ab-4516-4733-92ca-497cd84baf7f)

see that decrypted_response string in the screenshot

**Comment by jaitaiwan** [comment]
I don't have a clickbank account any more to test with; I'll likely need you to send through a test encrypted payload, and a key. Don't use a production one; goes without saying haha

**Comment by rajuaryan21** [comment]
Let me help you. You can use this URL to test: https://www.clickbank.com/tools/ins/

The secret Key is:  G3B7H7T87J2E0VFN

I have been scratching my head early from the morning trying to fix that, but no luck. Thank you so much for steping out to help.

**Comment by rajuaryan21** [comment]
The problem I have found is the "transactionTime" parameter they sent in the POST request. This is now in ISO 8601 format and is not being properly decoded into string after decryption. The rest of other parameters are fine in the body string. And hence is forming invalid JSON and not unmarshalling. Look at the screenshot in the previous message, you will have the idea. Perhaps, this info may help you fix it faster.

**Comment by jaitaiwan** [comment]
There's a bit more work to do in the PR, will update it further soon

**Comment by rajuaryan21** [comment]
Actually, I tried with that PKCS5 padding, but it didn't work in my case. Seems something else is off.

**Comment by rajuaryan21** [comment]
Below is the request body for version 7.0 IPN. You can try with this:

{{"notification":"AZgsJBHr1H1Ql6hxF4PULM+87WDsxFNwTKYXdINxl9UvdSkROcCYmGropPLY98Gc5RlhGM0EqEBUutxajsK8Kqk62SKpXS1AlfmS4Csz9dCaJRElX1XXtLAmjSCHu8wHhJlT7Ybq2dwTKj3Ywhl+TiNRMeX0+AzPzUnShqZIt1dKRmYc8DC/LHgvWcoES5IKwhsZDWQu6hOSC3FK/Bpt8QVV0JhhNMoqF20mjQXohPn8TcpLez8BzzKUMWYgxlm/iV0ctD7GU+923CdWKNOq6NYKc4As/GkZqhX1wB2hr2XQTs495s+/UgmFUCIBko6I4Kurdb+hNkuWI3A026HWzZ2YyfNdLXPtURF/gN6GOdqgrcsCR3vEpazVHSGJ32GX/vrj08yNG9cZKUC4VsvdrdIxjFip6Dd3pwaW1u6HveVn2PmSCbTVYMVL3ufHZIbBAb/Fcaj0RjPwBlPI/HSuwbA5b+7VcqCloVAeoyJT8o/O5fsKhwYFHSKC0szLVT5mK1E7CUqnDykSF3o8voWu3i2aI5equDM+cq3TkxQg82oydgBMtVWXXywbWC8ZUjtiiTJ7IwYx3kDpw/CQ6sXa4jOxN6ulcntlyWweV8fVrnLyiomGlskxu3GFMvNciZspL0M2ysiJl4mitDztzT1UNZ/lMwglQKwAfNXu510l1WEyhgBWtdoZT8lyIHXPWGNiZhHmxzKZzDgkz4IE1Vu6kgzhP24hQcn6dmBr1iZ5ayekHttSAX+OugDC5TG/mkpwH6EEkFXkp8svGsR4mXH/X/MjMItbWE6AbTQHrDhfuJkvulz8F52Ef3MLorqIbZNp+beiO8r7dfIFKp62FYElCjiGcNhZDv74yATGZaiBTx+/rl2MZ5XAturrqZgQtZuF2Xgtch/OAc3p+UHnP2i/AdK2OBCYY0fmhpjCdSKymIqCT5v1XfGobHPSsSGN9HZtY4SqjYDFRATnrPANAHlTYsPa9B+Qrx5Clk+sUqV6AAnVF8rrexKuOtW2k1tS/JLFyAKwaSyxFNgrJD2IXNnbqhxT3Q/orzVVJS0Fz6Ff/k//PePjMvpvX1QHt/HO3Hfg","iv":"NkE5NEI1OERGM0YzRDIyQw=="}}

**Comment by jaitaiwan** [comment]
Thanks, that'll make things a little faster. I had a few things to setup my side to debug

**Comment by jaitaiwan** [comment]
Thanks @rajuaryan21 I haven't been running the business for awhile.

So based on what you've sent me, it looks to me like there's something wrong with Clickbank's end... The fact that some of the data that's being decoded is coming back as valid json and the rest is just pure garbage indicates to me that pure garbage is being generated.

**Comment by rajuaryan21** [comment]
if that’s the case we can try to decode the information in PHP  or python or node and see if they too can’t decode it. What do you think?

**Comment by jaitaiwan** [comment]
That's what I'd do too. I may have a script to help with that

**Comment by jaitaiwan** [comment]
I used to have a php script but it's disappeared. Just use the example one on the ins documentation page and see how you go

**Comment by rajuaryan21** [comment]
ok, let me give it a try and update you.

**Comment by jaitaiwan** [comment]
How'd you go @rajuaryan21

**Comment by rajuaryan21** [comment]
Hey , just finished testing and found it working in php... Let me post you the details.

**Comment by rajuaryan21** [comment]
Here is the PHP script used to produce the result.

<?php


$handle = fopen("./chat.txt", "w+");

if(!$handle) {
    echo "Could not create handle";
}

// $post = '{"notification":"TR6oRInlNZ4Wg+se+8c1wcN/G/1sJ0xObOOLojbwylpOWZiZslQomEg4ztyJAJkvWZiC5tAqgQhiIrFRngZkwXdQ1jOsQ2/fpCdo+RTZDStdQZJqSnZSe8PaaW4UmP5+ib9i/SsRU2Cqa3N1uJDSJGcTYmBvD0DNeY8PsPfY3xhOh2BzF2auc3mZyNzy/crnJTOhnp6APycB3KCcDde1IKXkMIhjNjOU+ea3KspQZXESK3IzwnqS1ugeiCH6m3FJUI+DYHfg5vXBm0HV6l1kH5vx27WPObQVMw6VOVA4Wbxu/ZVCwm4ff12wFEvq1QwYhNCwaeq8XBevnLHkbWO3Om4nL7XjMR/iMcIfYMytdUh0pj3LuTbpYd2A+/EtGJzcFgUZ9QBXVsv0bvN9U2leS7X+mdNPOnJcYVjIBQt/Vuz8InLdy2CAUclP6sA4lkheZdhEgZrLHlktYOxP+lBaPhXxL/ooKytd85jEnnDrKjlbDY9ptMukI+rpDk+d6HJuoMLIy8P1t9aYAHIEsoEbjmderUJyCA2T5uSRLRRf9lHw0NH0KFNnbjJ/lVZjZXcSHdgvsqNDtKNewW2/uErBdIl+WPYxGrmqjdCilcZ7hyj6ZT4m/zvhw45T7ReBQuUAZjQkGErsSS2ZekvE1b6RKdxOM4RHmx7/LpTTEILyDddP6+F5JA83LdmNASheQxK9HGqOyy+3dZg3z0R80UCNkfkv2ZAQKid6ZrJJ+vunvDWAVXPX2quWKT+BDNT/orecbqIg6jkNkn9+7NsLAR0+f1vq8WHrNnYecAUWhxI2/ra8cTlfGRHNthz+D5P8ClpEOBxVS1ORXehO3lzY6A+o3nlkuM1s9chuh7FrxB3ovB0M/UOskt04wwy95l0Jfs94TTOOEFXAQSxlXNR8OsadlBfurf2fUCIBIRsMfAZL5LJMsDedSesOTtesUpgftbgrmydVcLjdiN27r4/bNjk5CmHIl8BNAC5LRVzWd3fiGkEjDDiGnSv6bmCjEbQIvCHL", "iv":"TTBFd1FUWkRNamxCUlE9PQ=="}';


$secretKey = "G3B7H7T87J2E0VFN"; //Secret Key from your ClickBank Account Settings > My Site > Advanced Tools


$message = json_decode(file_get_contents('php://input'));
// $message = json_decode($post);

// echo "message<pre>"; print_r($message); echo "</pre>";
 
 
fwrite($handle, print_r($message, true));


// AES/CBC/PKCS5Padding decryption
$encrypted = $message->{'notification'};
$iv = $message->{'iv'};
$decrypted = trim(mcrypt_decrypt(MCRYPT_RIJNDAEL_128,
                                 substr(sha1($secretKey), 0, 32),
                                 base64_decode($encrypted),
                                 MCRYPT_MODE_CBC,
                                 base64_decode($iv)), "\0..\32");
 

// echo "$decrypted<pre>"; echo $decrypted; echo "</pre>";

fwrite($handle, $decrypted);

// convert the decrypted string to a JSON object...
$order = json_decode($decrypted);

// echo "<pre>"; print_r($order); echo "</pre>";
fwrite($handle, print_r($order, true));


fclose($handle);
?>
---------------------------------

I realized the PHP code was able to successfully decrypt the notification. There were two IPN versions tested. The first one is version 6 which can be generated from this URL: https://www.clickbank.com/tools/ins/

notice the timestamp in this version 6 is in RFC 339 format. but I think this doesn't make any difference as this one too in Golang brings garbage output. Screenshot below:

![Screenshot from 2023-07-28 07-54-30](https://github.com/CentricWebEstate/clickbankgo/assets/3599630/daff8733-9ca1-4e6f-9a8c-2e8e0f76cc45)


The next INS version (7.0)  generated from my Clickbank dashboard has the timestamp in ISO8601 format. See the screenshot below. and this was also decrypted successfully in PHP

![Screenshot from 2023-07-28 08-05-28](https://github.com/CentricWebEstate/clickbankgo/assets/3599630/309f1d35-5b3e-43ff-a63f-b66a535525bc)


so my assumption is this timestamp is the real problem here and somewhere in the Golang decoding, this might be treated as a hexa value or maybe we need to decode URL values before decrypting...but this is the real problem...


If you look carefully at this piece of PHP code 

$decrypted = trim(mcrypt_decrypt(MCRYPT_RIJNDAEL_128,
                                 substr(sha1($secretKey), 0, 32),
                                 base64_decode($encrypted),
                                 MCRYPT_MODE_CBC,
                                 base64_decode($iv)), "\0..\32");

This is where all the magic is happening. We need to replicate the same thing in Golang and see the output. I don't really have much idea about encryption but started learning about it yesterday

Perhaps, this analysis could help us fix the issue. But, it's confirmed, the issue lies in Golang and not in Clickbank post.

What do you think?

**Comment by rajuaryan21** [comment]
[cb.txt](https://github.com/CentricWebEstate/clickbankgo/files/12189697/cb.txt)

sorry for that bad display...github parser..you know..I have attached the php script here in txt format. You can download and change the extention back to php and run.

**Comment by jaitaiwan** [comment]
@rajuaryan21 Good news! The PR I linked to this will fix it

**Comment by rajuaryan21** [comment]
WOW!!! Let me try...

**Comment by jaitaiwan** [comment]
There's two places that are examples of how to use, both the `cmd/cbg_example/cbg_example.go` command as well as the test in `test/integration_test.go`. Just if you're running `cbg_example` make sure that you specify the `-key=` argument to specify your own key.

**Comment by jaitaiwan** [comment]
Feel free to email me privately as well, love to hear where you're using this 👍

**Comment by rajuaryan21** [comment]
I see you added one function "StripCtrlChars" in cipher.go but it's not being used anywhere.  is it intentional? neither use of this function is mentioned in doc.

**Comment by rajuaryan21** [comment]
give me 2 mins..just testing it..

**Comment by rajuaryan21** [comment]
yeap...both working....v6 and v7 both worked..what was the problem?

**Comment by rajuaryan21** [comment]
I couldn't find your email...what's your email?

**Comment by jaitaiwan** [comment]
The problem was removing the beginning of the input by the aes blocksize. It should be on my github profile. Feel free to just message on twitter anyway.

**Comment by jaitaiwan** [comment]
I opened my dms up so it should work now
